### PR TITLE
Update Prune_database.py

### PR DESCRIPTION
**Pull request by kcwebby**
Also some "edits" from export_talkgroups.py that I forgot to roll back before committing the prune_database.py.  The changes to export_talkgroups.py result in just whitespace changes, as I was tinkering with the file to get the export to line up more with radio reference, and apparently put it back.

### CODE REVIEW

**Comment by dreinhold** [comment]
Thanks for the pull request!!!

**Comment by imagesafari** [comment]
Why set the timezone to UTC for prune_database? I would think that would go
against what the user is expecting, or certainly could.

**Comment by dreinhold** [comment]
That caught my eye also. I was thinking it was okay but now I think my assumption was based on the server OS having UTC as the set timezone.

The best fix would be to change
t = Transmission.objects.filter(start_datetime__lt=datetime.now(tz=timezone.utc) - timedelta(days=days_opt))
￼TO
t = Transmission.objects.filter(start_datetime__lt=timezone.now() - timedelta(days=days_opt))

Which will use the timezone set in the settings which should make it all match up.
￼

**Comment by kcwebby** [comment]
Ahh, even better.  I will update and setup a pull tomorrow.


Dylan, did you see my other email regarding some database fields and
questions ?   I got a non delivery notification, but my message was on the
web.

**Pull request merged**
